version: "3.9"
services:
  ml_notebook:
    container_name: ml_notebook
    build: ./ml_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./shared:/home/jovyan
    environment:
      - PASSWORD=ml
      - JUPYTER_TOKEN=ml
